apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
