---
kind: Service
apiVersion: v1
metadata:
  name: nfs-krb-server
  namespace: default
  labels:
    app: nfs-krb-server
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: nfs-krb-server
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
    - name: tcp-88
      port: 88
      protocol: TCP
    - name: tcp-749
      port: 749
      protocol: TCP 
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-krb-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-krb-server
  template:
    metadata:
      name: nfs-krb-server
      labels:
        app: nfs-krb-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: nfs-krb-server
          image: docker.io/thealmightydrawingtablet/nfs-krb:alpine
          env:
            - name: SHARED_DIRECTORY
              value: "/srv/shared"
            - name: NFS_KRB_REALM
              value: NFS-KRB-SERVER.DEFAULT.SVC.CLUSTER.LOCAL
            - name: NFS_KRB_PRINC
              value: nfs/nfs-krb-server.default.svc.cluster.local
            - name: NFS_KRB_PWD
              valueFrom:
                secretKeyRef:
                  name: krb-pwd
                  key: value
          volumeMounts:
            - mountPath: /srv/shared
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
            - name: udp-111
              containerPort: 111
              protocol: UDP
            - name: tcp-88
              containerPort: 88
              protocol: TCP
            - name: tcp-749
              containerPort: 749
              protocol: TCP
      volumes:
        - name: nfs-vol
          hostPath:
            path: /srv/nfs-krb-vol  # modify this to specify another path to store nfs share data
            type: DirectoryOrCreate
