apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: latest
    created: "2022-04-30T07:45:33.947314152Z"
    description: CSI NFS Driver for Kubernetes
    digest: a90874bcdaeef76bc10aea70f0ed559c69d50a9390d6c7d1b4156c4d54758c3b
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: v3.1.0
    created: "2022-04-30T07:45:33.949154964Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7e51bb9188b013195cafc265102fa365de9ec5513780e1dfc5363289f811a4d9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2022-04-30T07:45:33.94847026Z"
    description: CSI NFS Driver for Kubernetes
    digest: 44406231cd5cdada1c62a0541b93b4f5d5a70ccc8c50b33553a8692fe6cfae96
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2022-04-30T07:45:33.947715955Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a32c6fc016526fe19a0c9e0dfbe83d0ddde67ced533bb5f5d24d713f706c613
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: "2022-04-30T07:45:33.946482046Z"
