apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: v4.10.0
    created: "2025-01-23T13:44:25.195345831Z"
    description: CSI NFS Driver for Kubernetes
    digest: 9685daf9a5d4f87d46bf2343da0ad2ad26061802d596315e6677389226bd8319
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.10.0/csi-driver-nfs-v4.10.0.tgz
    version: v4.10.0
  - apiVersion: v1
    appVersion: v4.10.0
    created: "2025-01-23T13:44:25.191119952Z"
    description: CSI NFS Driver for Kubernetes
    digest: 3b8a02ed700b5756ea0ac00b32e58d2423485e5d199609788d307b9bf7c1f98c
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v4.10.0.tgz
    version: v4.10.0
  - apiVersion: v1
    appVersion: v4.9.0
    created: "2025-01-23T13:44:25.20480978Z"
    description: CSI NFS Driver for Kubernetes
    digest: 045f8c0995a657d2dcd7aa36fc16fd18315e23e68fc8cc4b328dcdc2e37a0c9a
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.9.0/csi-driver-nfs-v4.9.0.tgz
    version: v4.9.0
  - apiVersion: v1
    appVersion: v4.8.0
    created: "2025-01-23T13:44:25.203762057Z"
    description: CSI NFS Driver for Kubernetes
    digest: 6bcfc35f85ff56c20c464392e914c37818bc67b54f241f7c683bf6a2b5a675f7
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
    version: v4.8.0
  - apiVersion: v1
    appVersion: v4.7.0
    created: "2025-01-23T13:44:25.202778608Z"
    description: CSI NFS Driver for Kubernetes
    digest: b629c5fa9543223339952d9f7c478189c2e8f8695846f513b8d2a45ded7a5ac9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
    version: v4.7.0
  - apiVersion: v1
    appVersion: v4.6.0
    created: "2025-01-23T13:44:25.201696718Z"
    description: CSI NFS Driver for Kubernetes
    digest: c641e8ac0f86b631f07109c10e78c6aa893f57281c7bda595a78651e382e8648
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
    version: v4.6.0
  - apiVersion: v1
    appVersion: v4.5.0
    created: "2025-01-23T13:44:25.200631037Z"
    description: CSI NFS Driver for Kubernetes
    digest: 3d170cecde5a71fdf02b86c4c375b7818787c39311938e36199fb3e7a2d5162d
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
    version: v4.5.0
  - apiVersion: v1
    appVersion: v4.4.0
    created: "2025-01-23T13:44:25.199149976Z"
    description: CSI NFS Driver for Kubernetes
    digest: edb60e4ae8b0f94457d1425834567c0bd25ad4d63d30cf9400e71650279edca3
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.4.0/csi-driver-nfs-v4.4.0.tgz
    version: v4.4.0
  - apiVersion: v1
    appVersion: v4.3.0
    created: "2025-01-23T13:44:25.1972024Z"
    description: CSI NFS Driver for Kubernetes
    digest: 84202da067ec3672e75c41bbfd78e9cc95bc3bb81652ef68b84f71ee8a1b8f52
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.3.0/csi-driver-nfs-v4.3.0.tgz
    version: v4.3.0
  - apiVersion: v1
    appVersion: v4.2.0
    created: "2025-01-23T13:44:25.196241484Z"
    description: CSI NFS Driver for Kubernetes
    digest: e702f6c9be35f2649f5736ca5fcdc40ab1c6a235f41e7fb2472d208e8a5ebf47
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.2.0/csi-driver-nfs-v4.2.0.tgz
    version: v4.2.0
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2025-01-23T13:44:25.194499885Z"
    description: CSI NFS Driver for Kubernetes
    digest: b2baa2f129976cf2981c8873290aac509aa3c5937ffc319fbf69fbe3271c23eb
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.1.0/csi-driver-nfs-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2025-01-23T13:44:25.193795107Z"
    description: CSI NFS Driver for Kubernetes
    digest: 3145fd12225a639908b14675c8ae1f272bc0e57ffa2895b6f17411486a24229d
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.0.0/csi-driver-nfs-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: v3.1.0
    created: "2025-01-23T13:44:25.193100818Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7e51bb9188b013195cafc265102fa365de9ec5513780e1dfc5363289f811a4d9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2025-01-23T13:44:25.192389129Z"
    description: CSI NFS Driver for Kubernetes
    digest: 44406231cd5cdada1c62a0541b93b4f5d5a70ccc8c50b33553a8692fe6cfae96
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2025-01-23T13:44:25.191744921Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a32c6fc016526fe19a0c9e0dfbe83d0ddde67ced533bb5f5d24d713f706c613
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: "2025-01-23T13:44:25.19005881Z"
