image:
    nfs:
        repository: mcr.microsoft.com/k8s/csi/nfs-csi
        tag: latest
        pullPolicy: IfNotPresent
    csiProvisioner:
        repository: k8s.gcr.io/sig-storage/csi-provisioner
        tag: v2.2.2
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: k8s.gcr.io/sig-storage/livenessprobe
        tag: v2.4.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
        tag: v2.3.0
        pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-nfs-controller-sa # Name of Service Account to be created or used

rbac:
  create: true
  name: nfs

controller:
  name: csi-nfs-controller
  replicas: 2
  runOnMaster: false
  livenessProbe:
    healthPort: 29652
  logLevel: 5
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"

node:
  name: csi-nfs-node
  maxUnavailable: 1
  logLevel: 5
  livenessProbe:
    healthPort: 29653
  tolerations:
    - operator: "Exists"

feature:
  enableFSGroupPolicy: false

driver:
  name: nfs.csi.k8s.io

## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - name: "image-pull-secret"
